export const cards = [
  "Дурак / The Fool",
  "Маг / The Magician",
  "Верховная Жрица / The High Priestess",
  "Императрица / The Empress",
  "Император / The Emperor",
  "Иерофант / The Hierophant",
  "Влюбленные / The Lovers",
  "Колесница / The Chariot",
  "Сила / Strength",
  "Отшельник / The Hermit",
  "Колесо Фортуны / Wheel of Fortune",
  "Правосудие / Justice",
  "Повешенный / The Hanged Man",
  "Смерть / Death",
  "Умеренность / Temperance",
  "Дьявол / The Devil",
  "Башня / The Tower",
  "Звезда / The Star",
  "Луна / The Moon",
  "Солнце / The Sun",
  "Суд / Judgement",
  "Мир / The World",
  "Туз Жезлов / Ace of Wands",
  "Двойка Жезлов / Two of Wands",
  "Тройка Жезлов / Three of Wands",
  "Четверка Жезлов / Four of Wands",
  "Пятерка Жезлов / Five of Wands",
  "Шестерка Жезлов / Six of Wands",
  "Семерка Жезлов / Seven of Wands",
  "Восьмерка Жезлов / Eight of Wands",
  "Девятка Жезлов / Nine of Wands",
  "Десятка Жезлов / Ten of Wands",
  "Паж Жезлов / Page of Wands",
  "Рыцарь Жезлов / Knight of Wands",
  "Королева Жезлов / Queen of Wands",
  "Король Жезлов / King of Wands",
  "Туз Кубков / Ace of Cups",
  "Двойка Кубков / Two of Cups",
  "Тройка Кубков / Three of Cups",
  "Четверка Кубков / Four of Cups",
  "Пятерка Кубков / Five of Cups",
  "Шестерка Кубков / Six of Cups",
  "Семерка Кубков / Seven of Cups",
  "Восьмерка Кубков / Eight of Cups",
  "Девятка Кубков / Nine of Cups",
  "Десятка Кубков / Ten of Cups",
  "Паж Кубков / Page of Cups",
  "Рыцарь Кубков / Knight of Cups",
  "Королева Кубков / Queen of Cups",
  "Король Кубков / King of Cups",
  "Туз Мечей / Ace of Swords",
  "Двойка Мечей / Two of Swords",
  "Тройка Мечей / Three of Swords",
  "Четверка Мечей / Four of Swords",
  "Пятерка Мечей / Five of Swords",
  "Шестерка Мечей / Six of Swords",
  "Семерка Мечей / Seven of Swords",
  "Восьмерка Мечей / Eight of Swords",
  "Девятка Мечей / Nine of Swords",
  "Десятка Мечей / Ten of Swords",
  "Паж Мечей / Page of Swords",
  "Рыцарь Мечей / Knight of Swords",
  "Королева Мечей / Queen of Swords",
  "Король Мечей / King of Swords",
  "Туз Пентаклей / Ace of Pentacles",
  "Двойка Пентаклей / Two of Pentacles",
  "Тройка Пентаклей / Three of Pentacles",
  "Четверка Пентаклей / Four of Pentacles",
  "Пятерка Пентаклей / Five of Pentacles",
  "Шестерка Пентаклей / Six of Pentacles",
  "Семерка Пентаклей / Seven of Pentacles",
  "Восьмерка Пентаклей / Eight of Pentacles",
  "Девятка Пентаклей / Nine of Pentacles",
  "Десятка Пентаклей / Ten of Pentacles",
  "Паж Пентаклей / Page of Pentacles",
  "Рыцарь Пентаклей / Knight of Pentacles",
  "Королева Пентаклей / Queen of Pentacles",
  "Король Пентаклей / King of Pentacles",
];

export const imageMappings = {
  "Дурак / The Fool":
    "CAACAgQAAxkBAAOEZGeV4GXox2_-Gj1Qx1dSfOgkDMgAAggKAAJ812lSo75ZY9uNm2AvBA",
  "Маг / The Magician":
    "CAACAgQAAxkBAAOGZGeV890HwqvIdJF3_ScI_eINVpUAAhoIAALx9WlSfoL9jK6zIdcvBA",
  "Верховная Жрица / The High Priestess":
    "CAACAgQAAxkBAAOIZGeWDMNEkLXSCl4GDSgOB9CT5RAAApALAALCfmhS4NlCrQ_Jw50vBA",
  "Императрица / The Empress":
    "CAACAgQAAxkBAAOKZGeWGlG_PKA3ly048S_u2-JKvaMAAloIAAKgy2lSvusqhBORmHovBA",
  "Император / The Emperor":
    "CAACAgQAAxkBAAOMZGeWJ8QsEqeUsY26RXO_BA_drKAAAjoLAAJygWlSUpdNKkv0uHMvBA",
  "Иерофант / The Hierophant":
    "CAACAgQAAxkBAAOOZGeWNQac_er4o3PldjyXur5lZEcAArYIAAIHxmhSxpDHxiK5PQUvBA",
  "Влюбленные / The Lovers":
    "CAACAgQAAxkBAAOQZGeWSzZDhe0S-I1LFtImZJymaikAAoEIAAJhQGhSV21LNwkBTHAvBA",
  "Колесница / The Chariot":
    "CAACAgQAAxkBAAOSZGeWVgcRFi019-W94dVpE0k55XQAAtcIAAJ0p2hS_YX4UpeR8WUvBA",
  "Сила / Strength":
    "CAACAgQAAxkBAAOUZGeWbcnb_yyFRlFRrKVGrwO0qaMAAuIIAALeRWlS31AEPAblSVovBA",
  "Отшельник / The Hermit":
    "CAACAgQAAxkBAAOWZGeWf_uj2O7mEQLMUCBhD0J1cBMAAvAHAAITx3BSYTZ7CUe92tMvBA",
  "Колесо Фортуны / Wheel of Fortune":
    "CAACAgQAAxkBAAOYZGeWihmFPxbQPhUrNMU0NFnsw-oAAj0JAAIgk2lSAq8EcSk6i5wvBA",
  "Правосудие / Justice":
    "CAACAgQAAxkBAAOaZGeWlWHU-DcB3I_TBnxDCLDK2xcAAjILAAKA5WhSuxy8eR2XFJwvBA",
  "Повешенный / The Hanged Man":
    "CAACAgQAAxkBAAOcZGeWosSgyQvBeiInffRNdH_HqjUAAqUJAAIiCGhSaKbt9aRlAAHSLwQ",
  "Смерть / Death":
    "CAACAgQAAxkBAAOeZGeWsI5QOYphwAIFnUDTbmyw2jsAAs4JAAJVOGhSW_-r5iS14fcvBA",
  "Умеренность / Temperance":
    "CAACAgQAAxkBAAOgZGeWv6CAjeDExjoAAanOl_Q8qA59AAL-CQACJQ5oUuYDYPxITNwAAS8E",
  "Дьявол / The Devil":
    "CAACAgQAAxkBAAOiZGeWy8fLn6SoGf-Yevx7UTjgtYwAAh8IAAK5PGlSDFGSZHeEjQkvBA",
  "Башня / The Tower":
    "CAACAgQAAxkBAAOkZGeW2cos-KBhvCVV8rZcIJpHC4EAAqgIAAKm12lSz2YUj80d1YEvBA",
  "Звезда / The Star":
    "CAACAgQAAxkBAAOmZGeW47Y97A2UsCcbEn18GcXi2ksAAmQLAAKwF2lSNVjRMf3kBVIvBA",
  "Луна / The Moon":
    "CAACAgQAAxkBAAOoZGeW8mIBbMgTTnVnhAj2NK0QRfAAAngJAAJb1mhSY1pkQVMLW-QvBA",
  "Солнце / The Sun":
    "CAACAgQAAxkBAAOqZGeW_ZETGBges-cJrMLygOeLcnkAAj4JAALkIGhSuGQEHUoNvKAvBA",
  "Суд / Judgement":
    "CAACAgQAAxkBAAOsZGeXCMseJca9ykpM8HhDhDtJjMEAAngIAAIKO2lSyzg9PgvWWSIvBA",
  "Мир / The World":
    "CAACAgQAAxkBAAOuZGeXFuASJcskJJLTxdYsdPAgkfYAAgsIAAI-VnFSKYNvlyQRbMQvBA",
  "Туз Жезлов / Ace of Wands": null,
  "Двойка Жезлов / Two of Wands": null,
  "Тройка Жезлов / Three of Wands": null,
  "Четверка Жезлов / Four of Wands": null,
  "Пятерка Жезлов / Five of Wands": null,
  "Шестерка Жезлов / Six of Wands": null,
  "Семерка Жезлов / Seven of Wands": null,
  "Восьмерка Жезлов / Eight of Wands": null,
  "Девятка Жезлов / Nine of Wands": null,
  "Десятка Жезлов / Ten of Wands": null,
  "Паж Жезлов / Page of Wands": null,
  "Рыцарь Жезлов / Knight of Wands": null,
  "Королева Жезлов / Queen of Wands": null,
  "Король Жезлов / King of Wands": null,
  "Туз Кубков / Ace of Cups": null,
  "Двойка Кубков / Two of Cups": null,
  "Тройка Кубков / Three of Cups": null,
  "Четверка Кубков / Four of Cups": null,
  "Пятерка Кубков / Five of Cups": null,
  "Шестерка Кубков / Six of Cups": null,
  "Семерка Кубков / Seven of Cups": null,
  "Восьмерка Кубков / Eight of Cups": null,
  "Девятка Кубков / Nine of Cups": null,
  "Десятка Кубков / Ten of Cups": null,
  "Паж Кубков / Page of Cups": null,
  "Рыцарь Кубков / Knight of Cups": null,
  "Королева Кубков / Queen of Cups": null,
  "Король Кубков / King of Cups": null,
  "Туз Мечей / Ace of Swords": null,
  "Двойка Мечей / Two of Swords": null,
  "Тройка Мечей / Three of Swords": null,
  "Четверка Мечей / Four of Swords": null,
  "Пятерка Мечей / Five of Swords": null,
  "Шестерка Мечей / Six of Swords": null,
  "Семерка Мечей / Seven of Swords": null,
  "Восьмерка Мечей / Eight of Swords": null,
  "Девятка Мечей / Nine of Swords": null,
  "Десятка Мечей / Ten of Swords": null,
  "Паж Мечей / Page of Swords": null,
  "Рыцарь Мечей / Knight of Swords": null,
  "Королева Мечей / Queen of Swords": null,
  "Король Мечей / King of Swords": null,
  "Туз Пентаклей / Ace of Pentacles": null,
  "Двойка Пентаклей / Two of Pentacles": null,
  "Тройка Пентаклей / Three of Pentacles": null,
  "Четверка Пентаклей / Four of Pentacles": null,
  "Пятерка Пентаклей / Five of Pentacles": null,
  "Шестерка Пентаклей / Six of Pentacles": null,
  "Семерка Пентаклей / Seven of Pentacles": null,
  "Восьмерка Пентаклей / Eight of Pentacles": null,
  "Девятка Пентаклей / Nine of Pentacles": null,
  "Десятка Пентаклей / Ten of Pentacles": null,
  "Паж Пентаклей / Page of Pentacles": null,
  "Рыцарь Пентаклей / Knight of Pentacles": null,
  "Королева Пентаклей / Queen of Pentacles": null,
  "Король Пентаклей / King of Pentacles": null,
};
